[package]
name = "passwordtest-emergency"
version = "0.1.0"

[[module]]
name = "main"
source = "main.py"
interpreter = "python"
abi = "emscripten"  # Force WASM compatibility

[[static]]
source = "*.txt"
destination = "/data"

[fs]
"passlist.txt" = "/data/passlist.txt"
